name: Build Maven and Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Debug folder structure
        run: ls -R

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Maven package
        working-directory: java-maven-sonar-argocd-helm-k8s/sprint-boot-app
        run: mvn clean package --no-transfer-progress

      - name: Set Docker image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        working-directory: java-maven-sonar-argocd-helm-k8s/sprint-boot-app
        run: docker build -t my-app:${{ env.TAG }} .

      # Optional: Push image to DockerHub
      # - name: Log in to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push Docker image
      #   run: docker push my-app:${{ env.TAG }}
